name: Automate all scripts

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-feature-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch Raw data from open weather API
        run: python api.py
        
      - name: Train the model and find the best model
        run: python model.py
